spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.flywaydb.core.FlywayAutoConfiguration

app:
  jwt:
    secret: test-secret-please-override-test-secret-please-override
    expiration-ms: 900000

logging:
  level:
    org.springframework: WARN
    br.com.lumyra: INFO
